import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@gridstorm/core': path.resolve(__dirname, 'packages/core/src/index.ts'),
      '@gridstorm/dom-renderer': path.resolve(__dirname, 'packages/dom-renderer/src/index.ts'),
      '@gridstorm/license': path.resolve(__dirname, 'packages/license/src/index.ts'),
      '@gridstorm/i18n': path.resolve(__dirname, 'packages/i18n/src/index.ts'),
      '@gridstorm/theme-default': path.resolve(__dirname, 'packages/theme-default/src/index.ts'),
      '@gridstorm/react': path.resolve(__dirname, 'packages/react-adapter/src/index.ts'),
      '@gridstorm/vue': path.resolve(__dirname, 'packages/vue-adapter/src/index.ts'),
      '@gridstorm/svelte': path.resolve(__dirname, 'packages/svelte-adapter/src/index.ts'),
      '@gridstorm/angular': path.resolve(__dirname, 'packages/angular-adapter/src/index.ts'),
      '@gridstorm/pdf-core': path.resolve(__dirname, 'packages/pdf-core/src/index.ts'),
      '@gridstorm/pdf-renderer': path.resolve(__dirname, 'packages/pdf-renderer/src/index.ts'),
      '@gridstorm/pdf-theme': path.resolve(__dirname, 'packages/pdf-theme/src/index.ts'),
      '@gridstorm/pdf-plugin-text': path.resolve(__dirname, 'packages/pdf-plugin-text/src/index.ts'),
      '@gridstorm/pdf-plugin-pii': path.resolve(__dirname, 'packages/pdf-plugin-pii/src/index.ts'),
      '@gridstorm/pdf-plugin-form-fill': path.resolve(__dirname, 'packages/pdf-plugin-form-fill/src/index.ts'),
      '@gridstorm/pdf-plugin-intelligence': path.resolve(__dirname, 'packages/pdf-plugin-intelligence/src/index.ts'),
      '@gridstorm/plugin-sorting': path.resolve(__dirname, 'packages/plugin-sorting/src/index.ts'),
      '@gridstorm/plugin-filtering': path.resolve(__dirname, 'packages/plugin-filtering/src/index.ts'),
      '@gridstorm/plugin-selection': path.resolve(__dirname, 'packages/plugin-selection/src/index.ts'),
      '@gridstorm/plugin-editing': path.resolve(__dirname, 'packages/plugin-editing/src/index.ts'),
      '@gridstorm/plugin-pagination': path.resolve(__dirname, 'packages/plugin-pagination/src/index.ts'),
      '@gridstorm/plugin-grouping': path.resolve(__dirname, 'packages/plugin-grouping/src/index.ts'),
      '@gridstorm/plugin-aggregation': path.resolve(__dirname, 'packages/plugin-aggregation/src/index.ts'),
      '@gridstorm/plugin-column-resize': path.resolve(__dirname, 'packages/plugin-column-resize/src/index.ts'),
      '@gridstorm/plugin-column-pinning': path.resolve(__dirname, 'packages/plugin-column-pinning/src/index.ts'),
      '@gridstorm/plugin-column-reorder': path.resolve(__dirname, 'packages/plugin-column-reorder/src/index.ts'),
      '@gridstorm/plugin-column-autosize': path.resolve(__dirname, 'packages/plugin-column-autosize/src/index.ts'),
      '@gridstorm/plugin-context-menu': path.resolve(__dirname, 'packages/plugin-context-menu/src/index.ts'),
      '@gridstorm/plugin-clipboard': path.resolve(__dirname, 'packages/plugin-clipboard/src/index.ts'),
      '@gridstorm/plugin-conditional-formatting': path.resolve(__dirname, 'packages/plugin-conditional-formatting/src/index.ts'),
      '@gridstorm/plugin-sparklines': path.resolve(__dirname, 'packages/plugin-sparklines/src/index.ts'),
      '@gridstorm/plugin-charts': path.resolve(__dirname, 'packages/plugin-charts/src/index.ts'),
      '@gridstorm/plugin-status-bar': path.resolve(__dirname, 'packages/plugin-status-bar/src/index.ts'),
      '@gridstorm/plugin-ssrm': path.resolve(__dirname, 'packages/plugin-ssrm/src/index.ts'),
      '@gridstorm/plugin-master-detail': path.resolve(__dirname, 'packages/plugin-master-detail/src/index.ts'),
      '@gridstorm/plugin-cell-range': path.resolve(__dirname, 'packages/plugin-cell-range/src/index.ts'),
      '@gridstorm/plugin-time-travel': path.resolve(__dirname, 'packages/plugin-time-travel/src/index.ts'),
      '@gridstorm/plugin-streaming': path.resolve(__dirname, 'packages/plugin-streaming/src/index.ts'),
      '@gridstorm/plugin-validation': path.resolve(__dirname, 'packages/plugin-validation/src/index.ts'),
      '@gridstorm/plugin-excel-export': path.resolve(__dirname, 'packages/plugin-excel-export/src/index.ts'),
      '@gridstorm/plugin-pdf-export': path.resolve(__dirname, 'packages/plugin-pdf-export/src/index.ts'),
      '@gridstorm/plugin-ai': path.resolve(__dirname, 'packages/plugin-ai/src/index.ts'),
      // ── Next-gen plugins (Horizons 1-3) ──
      '@gridstorm/plugin-intent-engine': path.resolve(__dirname, 'packages/plugin-intent-engine/src/index.ts'),
      '@gridstorm/plugin-cell-formula': path.resolve(__dirname, 'packages/plugin-cell-formula/src/index.ts'),
      '@gridstorm/plugin-temporal': path.resolve(__dirname, 'packages/plugin-temporal/src/index.ts'),
      '@gridstorm/plugin-nl-query': path.resolve(__dirname, 'packages/plugin-nl-query/src/index.ts'),
      '@gridstorm/plugin-anomaly': path.resolve(__dirname, 'packages/plugin-anomaly/src/index.ts'),
      '@gridstorm/plugin-collab': path.resolve(__dirname, 'packages/plugin-collab/src/index.ts'),
      '@gridstorm/plugin-semantic': path.resolve(__dirname, 'packages/plugin-semantic/src/index.ts'),
      '@gridstorm/plugin-privacy-lens': path.resolve(__dirname, 'packages/plugin-privacy-lens/src/index.ts'),
      '@gridstorm/plugin-adaptive-renderer': path.resolve(__dirname, 'packages/plugin-adaptive-renderer/src/index.ts'),
      '@gridstorm/plugin-intelligence-hub': path.resolve(__dirname, 'packages/plugin-intelligence-hub/src/index.ts'),
      '@gridstorm/plugin-tree-data': path.resolve(__dirname, 'packages/plugin-tree-data/src/index.ts'),
      '@gridstorm/plugin-pivoting': path.resolve(__dirname, 'packages/plugin-pivoting/src/index.ts'),
      '@gridstorm/plugin-formula': path.resolve(__dirname, 'packages/plugin-formula/src/index.ts'),
      '@gridstorm/plugin-row-reorder': path.resolve(__dirname, 'packages/plugin-row-reorder/src/index.ts'),
      '@gridstorm/plugin-row-pinning': path.resolve(__dirname, 'packages/plugin-row-pinning/src/index.ts'),
      '@gridstorm/plugin-state-persistence': path.resolve(__dirname, 'packages/plugin-state-persistence/src/index.ts'),
      '@gridstorm/codemod': path.resolve(__dirname, 'packages/codemod/src/index.ts'),
      '@gridstorm/mcp-server': path.resolve(__dirname, 'packages/mcp-server/src/index.ts'),
      'gridstorm': path.resolve(__dirname, 'packages/gridstorm/src/index.ts'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: [
      'packages/*/src/**/*.test.{ts,tsx}',
      'packages/*/__tests__/**/*.test.{ts,tsx}',
      'examples/hub/__tests__/**/*.test.{ts,tsx}',
    ],
    coverage: {
      provider: 'v8',
      include: ['packages/*/src/**/*.ts'],
      exclude: ['**/*.test.ts', '**/index.ts', '**/*.d.ts'],
    },
  },
});
