// © 2025 GridStorm / Tekivex — All Rights Reserved
// Unauthorized reproduction or distribution is prohibited.
// ─── Row Node Types ───

/**
 * Represents a single row in the grid's internal data model.
 *
 * Row nodes wrap the original row data and add metadata for display,
 * selection, grouping, aggregation, and virtual scrolling. Every row
 * visible in the grid (including group rows and pinned rows) has a
 * corresponding `RowNode`.
 *
 * @typeParam TData - The type of the underlying row data object.
 *
 * @remarks
 * Row nodes use a mutable internal design for performance. The {@link version}
 * field is incremented on each change to enable targeted re-renders without
 * deep equality checks.
 *
 * @see {@link GridApi.getRowNode} to look up a node by ID.
 * @see {@link GridApi.forEachNode} to iterate over all nodes.
 */
export interface RowNode<TData = any> {
  /**
   * Unique row identifier.
   *
   * Generated by {@link GridConfig.getRowId} or defaults to the array index.
   * Used as the key in {@link GridState.rowNodes} and for selection tracking.
   */
  id: string;

  /**
   * Reference to the original row data object.
   *
   * `undefined` for group rows, filler rows, or loading placeholder rows.
   */
  data: TData | undefined;

  /**
   * Index in the original (unfiltered, unsorted) data array.
   *
   * Returns `-1` for group rows and other synthetic nodes that do not
   * correspond to a specific input data item.
   */
  sourceIndex: number;

  /**
   * Index in the displayed (post-filter/sort/group/pagination) row list.
   *
   * This index corresponds to the row's visual position in the grid
   * and is used by the virtual scroller.
   */
  displayIndex: number;

  /**
   * Nesting depth for tree/group data.
   *
   * `0` for top-level rows. Incremented by 1 for each nesting level
   * in grouped or tree-structured data.
   */
  level: number;

  // ── Display geometry ──

  /**
   * Height of this row in pixels, as resolved from {@link GridConfig.rowHeight}.
   */
  rowHeight: number;

  /**
   * Vertical offset (in pixels) from the top of the virtual scroll container.
   *
   * Used by the virtual scroller to position row elements via CSS `transform`.
   */
  rowTop: number;

  // ── Tree / Group ──

  /**
   * Parent group node, or `null` for top-level rows.
   *
   * @see {@link children}
   */
  parent: RowNode<TData> | null;

  /**
   * Child row nodes when this is a group row.
   * `null` for leaf (non-group) rows.
   */
  children: RowNode<TData>[] | null;

  /**
   * Whether this group row is currently expanded (children visible).
   * Always `false` for non-group rows.
   *
   * @default false
   * @see {@link GridApi.setRowNodeExpanded}
   */
  expanded: boolean;

  /**
   * `true` if this node represents a group row rather than a data row.
   *
   * Group rows are created by the grouping plugin when
   * {@link ColumnDef.rowGroup} is enabled on one or more columns.
   */
  group: boolean;

  /**
   * The column field that this group row represents.
   * `null` for non-group rows.
   */
  groupField: string | null;

  /**
   * The grouping value for this group row (e.g., the department name).
   * `undefined` for non-group rows.
   */
  groupValue: any;

  /**
   * Total number of leaf (non-group) descendant rows under this group.
   * `0` for non-group rows.
   */
  leafChildrenCount: number;

  // ── Aggregation ──

  /**
   * Aggregated data for this group row, keyed by column ID.
   *
   * Populated by the aggregation plugin when {@link ColumnDef.aggFunc}
   * is configured. `null` when no aggregation is active.
   *
   * @example
   * ```ts
   * // For a group row with aggFunc: 'sum' on 'salary' column:
   * node.aggData // { salary: 450000 }
   * ```
   */
  aggData: Record<string, any> | null;

  // ── Selection ──

  /** Whether this row is currently selected. */
  selected: boolean;

  /**
   * Whether this row can be selected.
   *
   * Set to `false` to prevent selection of specific rows
   * (e.g., group header rows or disabled rows).
   *
   * @default true
   */
  selectable: boolean;

  // ── Detail (master-detail) ──

  /**
   * `true` if this is a detail row in a master-detail layout.
   *
   * Detail rows expand below their master row and can contain
   * nested grids or custom content.
   */
  detail: boolean;

  // ── Pinning ──

  /**
   * Indicates whether this row is pinned to the top or bottom of the grid.
   *
   * - `'top'` - Pinned to the top (from {@link GridConfig.pinnedTopRowData}).
   * - `'bottom'` - Pinned to the bottom (from {@link GridConfig.pinnedBottomRowData}).
   * - `null` - Not pinned (normal scrolling row).
   */
  rowPinned: 'top' | 'bottom' | null;

  // ── Dirty tracking ──

  /**
   * Version counter incremented each time the node's properties change.
   *
   * Used by the renderer for targeted re-renders. Comparing versions
   * is cheaper than deep equality checks on the entire node.
   */
  version: number;
}

/**
 * Determines how the grid fetches and manages row data.
 *
 * - `'client'` - All data is loaded upfront into the browser.
 * - `'server'` - Data is fetched from a server in sorted/filtered pages.
 * - `'infinite'` - Rows are lazily loaded as the user scrolls down.
 * - `'viewport'` - Only rows currently visible in the viewport are fetched.
 *
 * @see {@link GridConfig.rowModelType}
 */
export type RowModelType = 'client' | 'server' | 'infinite' | 'viewport';

/**
 * Parameters passed to the {@link GridConfig.getRowId} callback
 * for generating unique row identifiers.
 *
 * @typeParam TData - The row data type.
 *
 * @example
 * ```ts
 * getRowId: (params: GetRowIdParams<Employee>) => String(params.data.employeeId)
 * ```
 */
export interface GetRowIdParams<TData = any> {
  /** The row data object for which to generate an ID. */
  data: TData;

  /** The zero-based index of this row in the input data array. */
  index: number;

  /**
   * Parent group keys when operating in a grouped/tree data model.
   *
   * An array of group key values from the root to the immediate parent.
   * Used to generate unique IDs for rows that appear under different
   * group hierarchies.
   *
   * @default undefined
   */
  parentKeys?: string[];
}

/**
 * Request payload sent to a server-side or infinite {@link DataSource}
 * when the grid needs to fetch rows.
 *
 * Contains the current sort model, filter model, pagination range,
 * and grouping/pivot configuration so the server can return the
 * correct data subset.
 *
 * @see {@link DataSource.getRows}
 */
export interface DataSourceRequest {
  /** The first row index to fetch (inclusive, zero-based). */
  startRow: number;

  /** The last row index to fetch (exclusive). */
  endRow: number;

  /** Current sort model to apply on the server. */
  sortModel: import('./column').SortModelItem[];

  /** Current filter model to apply on the server, keyed by column ID. */
  filterModel: Record<string, import('./filter').FilterModel>;

  /** Group keys identifying the expanded group path (for server-side grouping). */
  groupKeys: string[];

  /** Column IDs used for pivoting. */
  pivotCols: string[];

  /** Whether pivot mode is currently active. */
  pivotMode: boolean;

  /** Column IDs used as value columns (for aggregation in server-side mode). */
  valueCols: string[];

  /** Column IDs used for row grouping. */
  rowGroupCols: string[];
}

/**
 * Result returned by a {@link DataSource} after fetching rows.
 *
 * @typeParam TData - The row data type.
 */
export interface DataSourceResult<TData = any> {
  /** Array of row data objects for the requested range. */
  rowData: TData[];

  /** Number of rows returned in this result. */
  rowCount: number;

  /**
   * The index of the last row in the full dataset.
   *
   * When provided, tells the grid the total dataset size so it can
   * calculate scroll height. When omitted, the grid assumes more
   * rows may be available (infinite scrolling).
   *
   * @default undefined
   */
  lastRow?: number;
}

/**
 * Interface for server-side and infinite data sources.
 *
 * Implement this interface to provide data from an external source
 * (REST API, database, etc.) rather than loading all data into the browser.
 *
 * @typeParam TData - The row data type.
 *
 * @example
 * ```ts
 * const dataSource: DataSource<Employee> = {
 *   getRows: async (params) => {
 *     const response = await fetch(`/api/employees?start=${params.startRow}&end=${params.endRow}`);
 *     const data = await response.json();
 *     return { rowData: data.rows, rowCount: data.rows.length, lastRow: data.total };
 *   },
 * };
 * ```
 *
 * @see {@link GridConfig.dataSource}
 * @see {@link DataSourceRequest}
 * @see {@link DataSourceResult}
 */
export interface DataSource<TData = any> {
  /**
   * Fetches a range of rows from the data source.
   *
   * @param params - Request parameters including range, sort, filter, and grouping info.
   * @returns A promise resolving to the fetched row data and metadata.
   */
  getRows(params: DataSourceRequest): Promise<DataSourceResult<TData>>;

  /**
   * Optional cleanup function called when the grid is destroyed
   * or when the data source is replaced.
   */
  destroy?(): void;
}
