/**
 * Build all GridStorm example apps into a combined output folder.
 * Cross-platform Node.js replacement for build-all.sh.
 * Used by Vercel deployment.
 *
 * Vercel resolves outputDirectory ("dist") relative to the repo root,
 * so we output directly to <repo-root>/dist/.
 */
const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const SCRIPT_DIR = __dirname; // examples/ (absolute path of this script)
// Vercel sets CWD to the repo root (where vercel.json lives).
// Using process.cwd() guarantees dist/ ends up exactly where
// vercel.json#outputDirectory expects it, regardless of __dirname.
const ROOT_DIR = process.cwd();
const OUT_DIR = path.join(ROOT_DIR, 'dist');

console.log('Building GridStorm demos...');
console.log('Repo root:', ROOT_DIR);
console.log('Vercel root dir:', ROOT_DIR);
console.log('Output:', OUT_DIR);
console.log('CWD:', process.cwd());

// Clean output
if (fs.existsSync(OUT_DIR)) {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
}
fs.mkdirSync(OUT_DIR, { recursive: true });

function run(cmd, cwd) {
  console.log(`\n> ${cmd}`);
  console.log(`  cwd: ${cwd}`);
  try {
    execSync(cmd, { cwd, stdio: 'inherit', env: { ...process.env, NODE_ENV: 'production' } });
  } catch (err) {
    console.error(`\n✗ Command failed: ${cmd}`);
    console.error(`  Exit code: ${err.status}`);
    throw err;
  }
}

// Build hub (React SPA) — outputs to dist root (index.html + hub-assets/)
console.log('\n=== Building hub ===');
run(`npx vite build --outDir "${OUT_DIR}"`, path.join(SCRIPT_DIR, 'hub'));
console.log('Done: hub');

// Build each example app into dist/<app>/
const APPS = [
  'playground',
  'react-demo',
  'financial-trading',
  'spreadsheet',
  'analytics-explorer',
  'feature-showcase',
  'pdf-viewer',
  'cookbook',
];

for (const app of APPS) {
  const appDir = path.join(SCRIPT_DIR, app);
  if (!fs.existsSync(appDir)) {
    console.log(`\n⚠ Skipping ${app} (directory not found)`);
    continue;
  }
  console.log(`\n=== Building ${app} ===`);
  const appOutDir = path.join(OUT_DIR, app);
  run(`npx vite build --outDir "${appOutDir}"`, appDir);
  console.log(`Done: ${app}`);
}

// Build the Astro Starlight docs into dist/docs/.
// /docs/ → Astro Starlight docs (with sitemap-index.xml + sitemap-0.xml
// generated by @astrojs/sitemap, picked up by the root sitemap-index.xml
// that lives in examples/hub/public/).
//
// SKIP_DOCS=1 lets CI / local one-off runs opt out when the docs build
// isn't needed for the deploy under test.
if (process.env.SKIP_DOCS !== '1') {
  console.log('\n=== Building docs (Astro Starlight) ===');
  try {
    run(`npx astro build --outDir "${path.join(OUT_DIR, 'docs')}"`, path.join(ROOT_DIR, 'docs'));
    console.log('Done: docs');
  } catch (err) {
    console.error('⚠ docs build failed — continuing so other apps deploy.');
  }
} else {
  console.log('\n⏭  Skipping docs build (SKIP_DOCS=1)');
}

// Build both Storybooks into subpaths so the hub keeps the root.
// /storybook       → html-framework Storybook (core engine, plugins)
// /storybook-react → React-framework Storybook (<GridStorm/>, hooks, error boundary)
//
// SKIP_STORYBOOK=1 lets CI / local one-off runs opt out when the
// full storybook build is too slow (~2 min) and not under test.
if (process.env.SKIP_STORYBOOK !== '1') {
  console.log('\n=== Building Storybook (html framework) ===');
  try {
    run(
      `npx storybook build --output-dir "${path.join(OUT_DIR, 'storybook')}"`,
      ROOT_DIR
    );
    console.log('Done: storybook');
  } catch (err) {
    console.error('⚠ storybook build failed — continuing so other apps deploy.');
  }

  console.log('\n=== Building Storybook (React framework) ===');
  try {
    run(
      `npx storybook build --config-dir .storybook-react --output-dir "${path.join(OUT_DIR, 'storybook-react')}"`,
      ROOT_DIR
    );
    console.log('Done: storybook-react');
  } catch (err) {
    console.error('⚠ storybook-react build failed — continuing so other apps deploy.');
  }
} else {
  console.log('\n⏭  Skipping Storybook builds (SKIP_STORYBOOK=1)');
}

console.log('\nAll demos built successfully!');
console.log('Output directory:', OUT_DIR);
const entries = fs.readdirSync(OUT_DIR);
console.log('Output contents:', entries.join(', '));
