// © 2025 GridStorm / Tekivex — All Rights Reserved
// Unauthorized reproduction or distribution is prohibited.
//
// ─── @gridstorm/plugin-comments — Type model ───────────────────────────────
//
// CRDT-backed comment threads on grid cells. Built on the same Yjs
// transport pattern as @gridstorm/plugin-yjs-cells; consumers can either
// share the transport (one Y.Doc carries both cell edits AND comments) or
// run a separate one for comments.
//
// Comment data model:
//
//   A comment is identified by (anchor, commentId). `anchor` is the cell or
//   row the comment lives on:
//     • cell anchor: `${rowId}:${colId}` — granular, attaches to a single cell
//     • row anchor:  `${rowId}` — attaches to the row regardless of column
//
//   Inside the Y.Doc, there's a single top-level Y.Map called 'comments'.
//   Keys are anchors. Each value is a Y.Array<Y.Map<unknown>> — an ordered
//   list of comments on that anchor. Each Y.Map holds a single Comment.
//
//   Concurrent additions converge (Y.Array does deterministic insertion);
//   concurrent edits to the same comment body converge via Y.Map's
//   last-writer-wins on each field. (For body editing where character-level
//   merging matters, swap the body string for a Y.Text in a later phase.)

import type { CrdtTransport } from '@gridstorm/plugin-yjs-cells';
import type * as Y from 'yjs';

export interface CommentAuthor {
  /** Stable user identifier — usually from the IDP. */
  userId: string;
  /** Display name shown in the comment header. */
  displayName: string;
  /** Optional avatar URL. */
  avatarUrl?: string;
  /** Avatar tint, hex. */
  color?: string;
}

export interface Comment {
  /** Stable comment identifier — UUID-like, generated by the plugin. */
  id: string;
  /** Anchor this comment lives on. */
  anchor: string;
  /** Author of this comment. */
  author: CommentAuthor;
  /** Markdown body. */
  body: string;
  /** Wall-clock ms at creation. */
  createdAt: number;
  /** Wall-clock ms at last edit, if edited. */
  editedAt?: number;
  /** Whether this comment is resolved (UI affordance — does not delete). */
  resolved: boolean;
}

export interface CommentsPluginOptions {
  /** CRDT document identifier — shared across peers via the transport. */
  docId: string;
  /**
   * Optional transport. Omit to run as local-only (the Y.Doc still works,
   * comments just don't sync). Required for collaborative mode.
   */
  transport?: CrdtTransport;
  /**
   * Local author identity. Used as the `author` field on comments this
   * client creates. Required because comments are signed.
   */
  author: CommentAuthor;
  /**
   * Optional pre-existing Y.Doc to share with other plugins (e.g. the
   * same Doc as plugin-yjs-cells). Avoids opening two transports.
   */
  doc?: Y.Doc;
  /**
   * Local origin tag — same role as in plugin-yjs-cells. Auto-generated
   * if omitted.
   */
  origin?: string;
}

export interface CommentsState {
  connected: boolean;
  /** Map of anchor → comments[]. Read-only snapshot for consumers. */
  byAnchor: Map<string, Comment[]>;
  /** Total number of comments across all anchors. */
  total: number;
  /** Last error from the transport, if any. */
  lastError: Error | null;
  /** Local origin tag. */
  origin: string;
}

/** Anchor builders — cell anchors include the column, row anchors don't. */
export function cellAnchor(rowId: string, colId: string): string {
  return `${rowId}:${colId}`;
}
export function rowAnchor(rowId: string): string {
  return rowId;
}
